# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  train_data_ratio: 0.7
  val_data_ratio: 0.15
  test_data_ratio: 0.15
  window_size: 100  # Number of packets per window
  feature_list:
    - packet_length_mean
    - packet_length_std
    - packet_length_min
    - packet_length_max
    - inter_arrival_time_mean
    - inter_arrival_time_std
    - tcp_flags_distribution
    - protocol_distribution
    - port_distribution
    - packet_count_per_second
    - flow_duration
    - flow_bytes_per_second
    - flow_packets_per_second

# Model Configuration
model:
  name: "lightgbm"
  params:
    boosting_type: "goss"
    objective: "binary"
    metric: "auc"
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    bagging_fraction: 0.8
    bagging_freq: 5
    verbose: -1
  
  # Model compression settings
  compression:
    enable_quantization: true
    quantization_bits: 8
    enable_pruning: true
    target_model_size_mb: 5

# Training Configuration
training:
  batch_size: 1024
  num_epochs: 100
  early_stopping_rounds: 10
  random_seed: 42
  num_threads: 4  # For CPU training

# Real-time Detection Configuration
detection:
  inference_batch_size: 1
  max_inference_time_ms: 5
  confidence_threshold: 0.8
  interface: "eth0"  # Network interface to monitor
  pcap_buffer_size: 65536
  log_level: "INFO"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  log_level: "info"
  enable_docs: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/detection.log"
  max_file_size_mb: 100
  backup_count: 5 